### ISSUE TITLE
Remove unnecessary modules from app.profile.js

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-slurp-example#21]
I don't believe that [this line](https://github.com/tomwayson/esri-slurp-example/blob/master/profiles/app.profile.js#L88) is needed. The build system recursively traces the modules in main.js. I was hoping that removing that would reduce the size of the build, but the size was unchanged after I commented it out.

**Comment by tsamaya** [comment]
Exactly, I try both options (with and without) and don't see any diffrence at the first look.

If I understood, this part is only need when using dynamic loading (like we do in the dojo-bootstrap-map-js repo with operational layers defined in config.js => FeatureLayer, DynamicLayer).

**Comment by davewilton** [comment]
If you leave out that line all of the esri modules required in app/main.js will be embedded into the app/main.js rather than into dojo/dojo.js. The size of the build remains (roughly) the same but the distribution of the size is different. When left out main.js is 526kb (rather than 1.9kb) and dojo.js is 188kb (rather than 791kb)*. I can't see what is causing the 50kb difference though. 

Sorry if that's obvious, I was just trying to understand the line myself

*Your numbers may vary, I've been tweaking the app a bit

**Comment by tomwayson** [comment]
Closing as this repo is now deprecated. Use [bower build](https://developers.arcgis.com/javascript/jshelp/inside_bower_custom_builds.html) instead.

Report any issues to the [jsapi-resources repo](https://github.com/Esri/jsapi-resources/issues).
